[package]
name = "tinybeam"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "tinybeam"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.0-rc.0"
tiny_http = "0.7.0"
